const data = {
  products: [
    {
      _id: "1",
      name: "nike slim shirt",
      category: "shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock:10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas slim shirt",
      category: "shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock:0,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste free shirt",
      category: "shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock:30,
      brand: "Nike",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "nike slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock:20,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock:50,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id:"6",
      name:'Adidas Fit Pant',
      category:'Pant',
      image:'/images/p6.jpg',
      price:120,
      countInStock:70,
      brand:'Adidas',
      rating:4.5,
      numReviews:10,
      description:'high quality product',
    }
  ],
};
export default data;